from services.payment_gateways.base import PaymentGateway
from logger import logger


class UPIGateway(PaymentGateway):
    name = "upi_autopay"

    async def create_payment(self, user_id: int, plan: str):
        """
        Creates UPI Autopay intent.
        Actual payment link is generated by provider SDK/API.
        """
        if not self.is_available():
            raise RuntimeError("UPI payment under maintenance")

        self.log(f"Creating UPI payment user={user_id} plan={plan}")

        return {
            "provider": "upi",
            "user_id": user_id,
            "plan": plan,
            "intent_id": f"upi:{user_id}:{plan}"
        }

    async def verify_payment(self, payload: dict) -> bool:
        """
        Webhook payload verification.
        Signature check happens at webhook layer.
        """
        self.log(f"Verifying UPI payload={payload}")

        return payload.get("status") == "success"
